// <auto-generated />
namespace Pruebas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _789 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_789));
        
        string IMigrationMetadata.Id
        {
            get { return "202009051847512_789"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
